"""add description to groups

Revision ID: 62af28b7321e
Revises: c1955d494f08
Create Date: 2025-09-24 02:30:44.877740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62af28b7321e'
down_revision = 'c1955d494f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
