"""add password to user

Revision ID: 662c4785a923
Revises: 0512be2c0cbf
Create Date: 2025-09-24 22:16:28.923882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662c4785a923'
down_revision = '0512be2c0cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
